#include "src/game/envfx_snow.h"

const GeoLayout ccm_area_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, 579, 0, -9212, ccm_dl_Mountain_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 705, -57, -8219, ccm_dl_Mountain_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 3592, 467, -7791, ccm_dl_Mountain_002_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -4166, 190, -7747, ccm_dl_Mountain_003_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -4927, 730, -6181, ccm_dl_Mountain_004_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -69, -301, -937, ccm_dl_Mountain_005_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 10, 0, -9212, ccm_dl_Plane_001_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ccm_area_2[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_FLAMING_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 269, 403, 67074, 269, 303, 67074, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ccm_area_2_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_LAVA_BUBBLES, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(1, ccm_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
