extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern const GeoLayout ccm_area_2_geo[];
extern const GeoLayout ccm_area_2[];
extern const Collision ccm_area_2_collision[];
extern const MacroObject ccm_area_2_macro_objs[];
extern const GeoLayout ccm_area_3_geo[];
extern const GeoLayout ccm_area_3[];
extern const Collision ccm_area_3_collision[];
extern const MacroObject ccm_area_3_macro_objs[];
extern const GeoLayout ccm_area_4_geo[];
extern const GeoLayout ccm_area_4[];
extern const Collision ccm_area_4_collision[];
extern const MacroObject ccm_area_4_macro_objs[];
extern Lights1 ccm_dl_Snow_layer1_area1_lights;
extern Lights1 ccm_dl_snowVertexColor_lights;
extern Lights1 ccm_dl_snow_lights;
extern Lights1 ccm_dl_VisualMaterial120_f3d_lights;
extern Lights1 ccm_dl_VisualMaterial130_001_f3d_lights;
extern Lights1 ccm_dl_warpsnow_lights;
extern Lights1 ccm_dl_rock_lights;
extern Lights1 ccm_dl_lava_lights;
extern Lights1 ccm_dl_walls_lights;
extern Lights1 ccm_dl_warprock_lights;
extern Lights1 ccm_dl_rockScroll_lights;
extern u8 ccm_dl_SUPER_MARIO_64_E8E37186_0_2_all_ci8[];
extern u8 ccm_dl_SUPER_MARIO_64_E8E37186_0_2_all_ci8_pal_rgba16[];
extern u8 ccm_dl_SUPER_MARIO_64_E8E37186_0_2_all_ci8_copy[];
extern u8 ccm_dl_SUPER_MARIO_64_E8E37186_0_2_all_ci8_pal_rgba16_copy[];
extern u8 ccm_dl__12_ci8[];
extern u8 ccm_dl__12_ci8_pal_rgba16[];
extern u8 ccm_dl__13_ci8[];
extern u8 ccm_dl__13_ci8_pal_rgba16[];
extern u8 ccm_dl_Mountain_rock_dark_texture_i4[];
extern u8 ccm_dl_lava_rgba16[];
extern u8 ccm_dl_rockwall_i4[];
extern Vtx ccm_dl_Mountains_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountains_mesh_layer_1_vtx_0[15];
extern Gfx ccm_dl_Mountains_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountains_001_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountains_001_mesh_layer_1_vtx_0[15];
extern Gfx ccm_dl_Mountains_001_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountains_002_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountains_002_mesh_layer_1_vtx_0[15];
extern Gfx ccm_dl_Mountains_002_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_0[17];
extern Gfx ccm_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_1[28];
extern Gfx ccm_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Plane_mesh_layer_4_vtx_cull[8];
extern Vtx ccm_dl_Plane_mesh_layer_4_vtx_0[4];
extern Gfx ccm_dl_Plane_mesh_layer_4_tri_0[];
extern Vtx ccm_dl_Plane_mesh_layer_4_vtx_1[8];
extern Gfx ccm_dl_Plane_mesh_layer_4_tri_1[];
extern Vtx ccm_dl_Plane_mesh_layer_4_vtx_2[76];
extern Gfx ccm_dl_Plane_mesh_layer_4_tri_2[];
extern Vtx ccm_dl_Mountain_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountain_mesh_layer_1_vtx_0[5];
extern Gfx ccm_dl_Mountain_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountain_001_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountain_001_mesh_layer_1_vtx_0[5];
extern Gfx ccm_dl_Mountain_001_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountain_002_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountain_002_mesh_layer_1_vtx_0[5];
extern Gfx ccm_dl_Mountain_002_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountain_003_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountain_003_mesh_layer_1_vtx_0[5];
extern Gfx ccm_dl_Mountain_003_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountain_004_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountain_004_mesh_layer_1_vtx_0[5];
extern Gfx ccm_dl_Mountain_004_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountain_005_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountain_005_mesh_layer_1_vtx_0[22];
extern Gfx ccm_dl_Mountain_005_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_001_mesh_layer_1_vtx_0[50];
extern Gfx ccm_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_001_mesh_layer_1_vtx_1[20];
extern Gfx ccm_dl_Plane_001_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Plane_001_mesh_layer_1_vtx_2[58];
extern Gfx ccm_dl_Plane_001_mesh_layer_1_tri_2[];
extern Vtx ccm_dl_Plane_001_mesh_layer_1_vtx_3[79];
extern Gfx ccm_dl_Plane_001_mesh_layer_1_tri_3[];
extern Vtx ccm_dl_Plane_002_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_002_mesh_layer_1_vtx_0[169];
extern Gfx ccm_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_002_mesh_layer_1_vtx_1[4];
extern Gfx ccm_dl_Plane_002_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Plane_003_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_003_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_Plane_003_mesh_layer_1_tri_0[];
extern Gfx mat_ccm_dl_Snow_layer1_area1[];
extern Gfx mat_revert_ccm_dl_Snow_layer1_area1[];
extern Gfx mat_ccm_dl_snowVertexColor[];
extern Gfx mat_revert_ccm_dl_snowVertexColor[];
extern Gfx mat_ccm_dl_snow[];
extern Gfx mat_revert_ccm_dl_snow[];
extern Gfx mat_ccm_dl_VisualMaterial120_f3d[];
extern Gfx mat_revert_ccm_dl_VisualMaterial120_f3d[];
extern Gfx mat_ccm_dl_VisualMaterial130_001_f3d[];
extern Gfx mat_revert_ccm_dl_VisualMaterial130_001_f3d[];
extern Gfx mat_ccm_dl_warpsnow[];
extern Gfx mat_revert_ccm_dl_warpsnow[];
extern Gfx mat_ccm_dl_rock[];
extern Gfx mat_revert_ccm_dl_rock[];
extern Gfx mat_ccm_dl_lava[];
extern Gfx mat_ccm_dl_walls[];
extern Gfx mat_revert_ccm_dl_walls[];
extern Gfx mat_ccm_dl_warprock[];
extern Gfx mat_revert_ccm_dl_warprock[];
extern Gfx mat_ccm_dl_rockScroll[];
extern Gfx mat_revert_ccm_dl_rockScroll[];
extern Gfx ccm_dl_Mountains_mesh_layer_1[];
extern Gfx ccm_dl_Mountains_001_mesh_layer_1[];
extern Gfx ccm_dl_Mountains_002_mesh_layer_1[];
extern Gfx ccm_dl_Plane_mesh_layer_1[];
extern Gfx ccm_dl_Plane_mesh_layer_4[];
extern Gfx ccm_dl_Mountain_mesh_layer_1[];
extern Gfx ccm_dl_Mountain_001_mesh_layer_1[];
extern Gfx ccm_dl_Mountain_002_mesh_layer_1[];
extern Gfx ccm_dl_Mountain_003_mesh_layer_1[];
extern Gfx ccm_dl_Mountain_004_mesh_layer_1[];
extern Gfx ccm_dl_Mountain_005_mesh_layer_1[];
extern Gfx ccm_dl_Plane_001_mesh_layer_1[];
extern Gfx ccm_dl_Plane_002_mesh_layer_1[];
extern Gfx ccm_dl_Plane_003_mesh_layer_1[];
extern Gfx ccm_dl_material_revert_render_settings[];
