extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern const GeoLayout ccm_area_2_geo[];
extern const GeoLayout ccm_area_2[];
extern const Collision ccm_area_2_collision[];
extern const MacroObject ccm_area_2_macro_objs[];
extern const GeoLayout ccm_area_3_geo[];
extern const GeoLayout ccm_area_3[];
extern const Collision ccm_area_3_collision[];
extern const MacroObject ccm_area_3_macro_objs[];
extern const GeoLayout ccm_area_4_geo[];
extern const GeoLayout ccm_area_4[];
extern const Collision ccm_area_4_collision[];
extern const MacroObject ccm_area_4_macro_objs[];
extern const GeoLayout ccm_area_5_geo[];
extern const GeoLayout ccm_area_5[];
extern const Collision ccm_area_5_collision[];
extern const MacroObject ccm_area_5_macro_objs[];
extern const GeoLayout ccm_area_6_geo[];
extern const GeoLayout ccm_area_6[];
extern const Collision ccm_area_6_collision[];
extern const MacroObject ccm_area_6_macro_objs[];
extern const GeoLayout ccm_area_7_geo[];
extern const GeoLayout ccm_area_7[];
extern const Collision ccm_area_7_collision[];
extern const MacroObject ccm_area_7_macro_objs[];
extern Lights1 ccm_dl_Snow_layer1_area1_lights;
extern Lights1 ccm_dl_snowVertexColor_lights;
extern Lights1 ccm_dl_snow_layer1_area1_lights;
extern Lights1 ccm_dl_VisualMaterial120_f3d_lights;
extern Lights1 ccm_dl_VisualMaterial130_001_f3d_lights;
extern Lights1 ccm_dl_warpsnow_layer1_area1_lights;
extern Lights1 ccm_dl_rock_lights;
extern Lights1 ccm_dl_lava_lights;
extern Lights1 ccm_dl_walls_lights;
extern Lights1 ccm_dl_warprock_lights;
extern Lights1 ccm_dl_rockScroll_lights;
extern Lights1 ccm_dl_rockwarp_lights;
extern Lights1 ccm_dl_Snow_001_layer1_area5_lights;
extern Lights1 ccm_dl_SnowWarp_layer1_area5_lights;
extern Lights1 ccm_dl_HangableCeiling_layer4_area5_lights;
extern Lights1 ccm_dl_Cube_layer1_area6_lights;
extern Lights1 ccm_dl_RockVertex_layer1_area6_lights;
extern Lights1 ccm_dl_Slide_layer1_area6_lights;
extern Lights1 ccm_dl_RockWarp_layer1_area6_lights;
extern Lights1 ccm_dl_Snow_002_layer1_area7_lights;
extern Lights1 ccm_dl_SnowWall_001_layer1_area7_lights;
extern u8 ccm_dl_SUPER_MARIO_64_E8E37186_0_2_all_ci8[];
extern u8 ccm_dl_SUPER_MARIO_64_E8E37186_0_2_all_ci8_pal_rgba16[];
extern u8 ccm_dl_SUPER_MARIO_64_E8E37186_0_2_all_ci8_copy[];
extern u8 ccm_dl_SUPER_MARIO_64_E8E37186_0_2_all_ci8_pal_rgba16_copy[];
extern u8 ccm_dl__12_ci8[];
extern u8 ccm_dl__12_ci8_pal_rgba16[];
extern u8 ccm_dl__13_ci8[];
extern u8 ccm_dl__13_ci8_pal_rgba16[];
extern u8 ccm_dl_Mountain_rock_dark_texture_i4[];
extern u8 ccm_dl_lava_rgba16[];
extern u8 ccm_dl_rockwall_i4[];
extern u8 ccm_dl_SUPER_MARIO_64_79D25AFB_0_2_all_ci8[];
extern u8 ccm_dl_SUPER_MARIO_64_79D25AFB_0_2_all_ci8_pal_rgba16[];
extern u8 ccm_dl_SUPER_MARIO_64_7AE8E843_0_2_all_i8[];
extern u8 ccm_dl_stone_wall_covered_with_white_snow_HGC3AB_ci4[];
extern u8 ccm_dl_stone_wall_covered_with_white_snow_HGC3AB_ci4_pal_rgba16[];
extern Vtx ccm_dl_Mountains_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountains_mesh_layer_1_vtx_0[15];
extern Gfx ccm_dl_Mountains_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountains_001_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountains_001_mesh_layer_1_vtx_0[15];
extern Gfx ccm_dl_Mountains_001_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountains_002_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountains_002_mesh_layer_1_vtx_0[15];
extern Gfx ccm_dl_Mountains_002_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_0[17];
extern Gfx ccm_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_1[28];
extern Gfx ccm_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_2[76];
extern Gfx ccm_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx ccm_dl_Plane_mesh_layer_4_vtx_cull[8];
extern Vtx ccm_dl_Plane_mesh_layer_4_vtx_0[4];
extern Gfx ccm_dl_Plane_mesh_layer_4_tri_0[];
extern Vtx ccm_dl_Plane_mesh_layer_4_vtx_1[8];
extern Gfx ccm_dl_Plane_mesh_layer_4_tri_1[];
extern Vtx ccm_dl_Mountain_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountain_mesh_layer_1_vtx_0[5];
extern Gfx ccm_dl_Mountain_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountain_001_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountain_001_mesh_layer_1_vtx_0[5];
extern Gfx ccm_dl_Mountain_001_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountain_002_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountain_002_mesh_layer_1_vtx_0[5];
extern Gfx ccm_dl_Mountain_002_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountain_003_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountain_003_mesh_layer_1_vtx_0[5];
extern Gfx ccm_dl_Mountain_003_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountain_004_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountain_004_mesh_layer_1_vtx_0[5];
extern Gfx ccm_dl_Mountain_004_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountain_005_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountain_005_mesh_layer_1_vtx_0[22];
extern Gfx ccm_dl_Mountain_005_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_001_mesh_layer_1_vtx_0[50];
extern Gfx ccm_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_001_mesh_layer_1_vtx_1[20];
extern Gfx ccm_dl_Plane_001_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Plane_001_mesh_layer_1_vtx_2[58];
extern Gfx ccm_dl_Plane_001_mesh_layer_1_tri_2[];
extern Vtx ccm_dl_Plane_001_mesh_layer_1_vtx_3[79];
extern Gfx ccm_dl_Plane_001_mesh_layer_1_tri_3[];
extern Vtx ccm_dl_Mountains_004_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountains_004_mesh_layer_1_vtx_0[15];
extern Gfx ccm_dl_Mountains_004_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountains_005_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountains_005_mesh_layer_1_vtx_0[15];
extern Gfx ccm_dl_Mountains_005_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_002_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_002_mesh_layer_1_vtx_0[176];
extern Gfx ccm_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_002_mesh_layer_1_vtx_1[4];
extern Gfx ccm_dl_Plane_002_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Plane_003_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_003_mesh_layer_1_vtx_0[56];
extern Gfx ccm_dl_Plane_003_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_003_mesh_layer_1_vtx_1[20];
extern Gfx ccm_dl_Plane_003_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Mountains_003_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountains_003_mesh_layer_1_vtx_0[20];
extern Gfx ccm_dl_Mountains_003_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_004_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_004_mesh_layer_1_vtx_0[463];
extern Gfx ccm_dl_Plane_004_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_004_mesh_layer_1_vtx_1[4];
extern Gfx ccm_dl_Plane_004_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Plane_006_mesh_layer_4_vtx_cull[8];
extern Vtx ccm_dl_Plane_006_mesh_layer_4_vtx_0[16];
extern Gfx ccm_dl_Plane_006_mesh_layer_4_tri_0[];
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Cube_001_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_002_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Cube_002_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_003_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Cube_003_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_Cube_003_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_004_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Cube_004_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_Cube_004_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_005_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Cube_005_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_Cube_005_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountain_006_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountain_006_mesh_layer_1_vtx_0[5];
extern Gfx ccm_dl_Mountain_006_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountain_007_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountain_007_mesh_layer_1_vtx_0[5];
extern Gfx ccm_dl_Mountain_007_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mountain_008_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mountain_008_mesh_layer_1_vtx_0[5];
extern Gfx ccm_dl_Mountain_008_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_007_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_007_mesh_layer_1_vtx_0[240];
extern Gfx ccm_dl_Plane_007_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_007_mesh_layer_1_vtx_1[12];
extern Gfx ccm_dl_Plane_007_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Plane_007_mesh_layer_1_vtx_2[4];
extern Gfx ccm_dl_Plane_007_mesh_layer_1_tri_2[];
extern Vtx ccm_dl_Plane_008_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_008_mesh_layer_1_vtx_0[48];
extern Gfx ccm_dl_Plane_008_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_008_mesh_layer_1_vtx_1[52];
extern Gfx ccm_dl_Plane_008_mesh_layer_1_tri_1[];
extern Gfx mat_ccm_dl_Snow_layer1_area1[];
extern Gfx mat_revert_ccm_dl_Snow_layer1_area1[];
extern Gfx mat_ccm_dl_snowVertexColor[];
extern Gfx mat_revert_ccm_dl_snowVertexColor[];
extern Gfx mat_ccm_dl_snow_layer1_area1[];
extern Gfx mat_revert_ccm_dl_snow_layer1_area1[];
extern Gfx mat_ccm_dl_VisualMaterial120_f3d[];
extern Gfx mat_revert_ccm_dl_VisualMaterial120_f3d[];
extern Gfx mat_ccm_dl_VisualMaterial130_001_f3d[];
extern Gfx mat_revert_ccm_dl_VisualMaterial130_001_f3d[];
extern Gfx mat_ccm_dl_warpsnow_layer1_area1[];
extern Gfx mat_revert_ccm_dl_warpsnow_layer1_area1[];
extern Gfx mat_ccm_dl_rock[];
extern Gfx mat_revert_ccm_dl_rock[];
extern Gfx mat_ccm_dl_lava[];
extern Gfx mat_ccm_dl_walls[];
extern Gfx mat_revert_ccm_dl_walls[];
extern Gfx mat_ccm_dl_warprock[];
extern Gfx mat_revert_ccm_dl_warprock[];
extern Gfx mat_ccm_dl_rockScroll[];
extern Gfx mat_revert_ccm_dl_rockScroll[];
extern Gfx mat_ccm_dl_rockwarp[];
extern Gfx mat_revert_ccm_dl_rockwarp[];
extern Gfx mat_ccm_dl_Snow_001_layer1_area5[];
extern Gfx mat_revert_ccm_dl_Snow_001_layer1_area5[];
extern Gfx mat_ccm_dl_SnowWarp_layer1_area5[];
extern Gfx mat_revert_ccm_dl_SnowWarp_layer1_area5[];
extern Gfx mat_ccm_dl_HangableCeiling_layer4_area5[];
extern Gfx mat_revert_ccm_dl_HangableCeiling_layer4_area5[];
extern Gfx mat_ccm_dl_Cube_layer1_area6[];
extern Gfx mat_revert_ccm_dl_Cube_layer1_area6[];
extern Gfx mat_ccm_dl_RockVertex_layer1_area6[];
extern Gfx mat_revert_ccm_dl_RockVertex_layer1_area6[];
extern Gfx mat_ccm_dl_Slide_layer1_area6[];
extern Gfx mat_revert_ccm_dl_Slide_layer1_area6[];
extern Gfx mat_ccm_dl_RockWarp_layer1_area6[];
extern Gfx mat_revert_ccm_dl_RockWarp_layer1_area6[];
extern Gfx mat_ccm_dl_Snow_002_layer1_area7[];
extern Gfx mat_revert_ccm_dl_Snow_002_layer1_area7[];
extern Gfx mat_ccm_dl_SnowWall_001_layer1_area7[];
extern Gfx mat_revert_ccm_dl_SnowWall_001_layer1_area7[];
extern Gfx ccm_dl_Mountains_mesh_layer_1[];
extern Gfx ccm_dl_Mountains_001_mesh_layer_1[];
extern Gfx ccm_dl_Mountains_002_mesh_layer_1[];
extern Gfx ccm_dl_Plane_mesh_layer_1[];
extern Gfx ccm_dl_Plane_mesh_layer_4[];
extern Gfx ccm_dl_Mountain_mesh_layer_1[];
extern Gfx ccm_dl_Mountain_001_mesh_layer_1[];
extern Gfx ccm_dl_Mountain_002_mesh_layer_1[];
extern Gfx ccm_dl_Mountain_003_mesh_layer_1[];
extern Gfx ccm_dl_Mountain_004_mesh_layer_1[];
extern Gfx ccm_dl_Mountain_005_mesh_layer_1[];
extern Gfx ccm_dl_Plane_001_mesh_layer_1[];
extern Gfx ccm_dl_Mountains_004_mesh_layer_1[];
extern Gfx ccm_dl_Mountains_005_mesh_layer_1[];
extern Gfx ccm_dl_Plane_002_mesh_layer_1[];
extern Gfx ccm_dl_Plane_003_mesh_layer_1[];
extern Gfx ccm_dl_Mountains_003_mesh_layer_1[];
extern Gfx ccm_dl_Plane_004_mesh_layer_1[];
extern Gfx ccm_dl_Plane_006_mesh_layer_4[];
extern Gfx ccm_dl_Cube_mesh_layer_1[];
extern Gfx ccm_dl_Cube_001_mesh_layer_1[];
extern Gfx ccm_dl_Cube_002_mesh_layer_1[];
extern Gfx ccm_dl_Cube_003_mesh_layer_1[];
extern Gfx ccm_dl_Cube_004_mesh_layer_1[];
extern Gfx ccm_dl_Cube_005_mesh_layer_1[];
extern Gfx ccm_dl_Mountain_006_mesh_layer_1[];
extern Gfx ccm_dl_Mountain_007_mesh_layer_1[];
extern Gfx ccm_dl_Mountain_008_mesh_layer_1[];
extern Gfx ccm_dl_Plane_007_mesh_layer_1[];
extern Gfx ccm_dl_Plane_008_mesh_layer_1[];
extern Gfx ccm_dl_material_revert_render_settings[];
