#include "src/game/envfx_snow.h"

const GeoLayout bob_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, 0, 375, 0, bob_dl_Fountain_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_Fountain_mesh),
			GEO_DISPLAY_LIST(5, bob_dl_Water_mesh_layer_5),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -3094, 749, -2667, bob_dl_House_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(4, 1088, 718, -15, bob_dl_Window_mesh_layer_4),
			GEO_TRANSLATE_NODE_WITH_DL(4, 592, 75, 880, bob_dl_Window_001_mesh_layer_4),
			GEO_TRANSLATE_NODE_WITH_DL(4, -459, 75, 880, bob_dl_Window_002_mesh_layer_4),
			GEO_TRANSLATE_NODE_WITH_DL(4, -544, 88, -880, bob_dl_Window_003_mesh_layer_4),
			GEO_TRANSLATE_NODE_WITH_DL(4, 507, 88, -880, bob_dl_Window_004_mesh_layer_4),
			GEO_TRANSLATE_NODE_WITH_DL(4, -1053, 718, -15, bob_dl_Window_005_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, 4629, 2004, -13942, bob_dl_Mountains_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 28, 100, -37, bob_dl_Plane_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 5212, 3069, -479, bob_dl_Toad_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bob_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, -759, 0, 0, -859, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bob_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(1, bob_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, bob_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, bob_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
