#include "src/game/envfx_snow.h"

const GeoLayout bob_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, 28, 100, -37, bob_dl_MainTerrain_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(1, -264, 218, 37, bob_dl_Fountain_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, bob_dl_Fountain_mesh_layer_5),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_Fountain_mesh),
				GEO_DISPLAY_LIST(5, bob_dl_Water_mesh_layer_5),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(1, -3962, 422, 14, bob_dl_House_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_NODE_WITH_DL(4, 706, 466, -10, bob_dl_Window_mesh_layer_4),
				GEO_TRANSLATE_NODE_WITH_DL(4, -298, 48, 571, bob_dl_Window_001_mesh_layer_4),
				GEO_TRANSLATE_NODE_WITH_DL(4, 384, 48, 571, bob_dl_Window_002_mesh_layer_4),
				GEO_TRANSLATE_NODE_WITH_DL(4, 329, 57, -571, bob_dl_Window_003_mesh_layer_4),
				GEO_TRANSLATE_NODE_WITH_DL(4, -353, 57, -571, bob_dl_Window_004_mesh_layer_4),
				GEO_TRANSLATE_NODE_WITH_DL(4, -683, 466, -10, bob_dl_Window_005_mesh_layer_4),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(1, -3603, 421, 4639, bob_dl_House_001_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_NODE_WITH_DL(4, 566, 466, -421, bob_dl_Window_012_mesh_layer_4),
				GEO_TRANSLATE_NODE_WITH_DL(4, 92, 48, 637, bob_dl_Window_013_mesh_layer_4),
				GEO_TRANSLATE_NODE_WITH_DL(4, 645, 48, 238, bob_dl_Window_014_mesh_layer_4),
				GEO_TRANSLATE_NODE_WITH_DL(4, -67, 57, -655, bob_dl_Window_015_mesh_layer_4),
				GEO_TRANSLATE_NODE_WITH_DL(4, -620, 57, -256, bob_dl_Window_016_mesh_layer_4),
				GEO_TRANSLATE_NODE_WITH_DL(4, -559, 466, 392, bob_dl_Window_017_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, 4629, 2004, -13942, bob_dl_Mountains_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 28, 100, -37, bob_dl_PathMountainsDecorative_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 4816, 1698, -193, bob_dl_ToadTower_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -399, 4654, 15098, bob_dl_Volcano_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bob_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, -759, 0, 0, -859, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bob_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, bob_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, bob_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, bob_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
